import json
from pathlib import Path
import re
from typing import Any

from thirdparty import RecipeBase, RecipeOptions
from thirdparty.apple import is_apple_os
from thirdparty.cmake import CMake, CMakeToolchain
from thirdparty.files import copy, get, load, rmdir, save
from thirdparty.scm import Version
from thirdparty.scm.github import GithubRepository


class _Options(RecipeOptions):
    shared: bool = False
    pic: bool = True


class Recipe(RecipeBase[_Options]):
    name = "abseil"
    version = "20260526.0"
    license = "Apache-2.0"

    def latest_version(self):
        repo = GithubRepository(self, "abseil/abseil-cpp")
        return Version(repo.latest_release)

    def requirements(self):
        self.requires_tool("cmake")

    def source(self):
        get(
            self,
            url=f"https://github.com/abseil/abseil-cpp/archive/{self.version}.tar.gz",
            sha256="6e1aee535473414164bf83e4ebc40240dec71a4701f8a642d906e95bea1aea0c",
            destination=self.folders.source,
            strip_root=True)

    def generate(self):
        tc = CMakeToolchain(self)
        tc.cache_variables["ABSL_ENABLE_INSTALL"] = True
        tc.cache_variables["ABSL_PROPAGATE_CXX_STD"] = True
        tc.cache_variables["BUILD_TESTING"] = False
        if self.settings.os == "Windows" and self.settings.compiler in ["msvc", "clang"] and self.settings.compiler_runtime:
            runtime = str(self.settings.compiler_runtime)
            tc.cache_variables["ABSL_MSVC_STATIC_RUNTIME"] = runtime == "static"
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        copy(self, "LICENSE", src=self.folders.source, dst=self.folders.package / "licenses")
        cmake = CMake(self)
        cmake.install()
        rmdir(self, self.folders.package / "lib" / "pkgconfig")

        # Load components hierarchy before removing CMake files generated by abseil installation
        cmake_folder = self.folders.package / "lib" / "cmake"
        absl_targets_file = cmake_folder / "absl" / "abslTargets.cmake"
        components = self._load_components_from_cmake_target_file(absl_targets_file)
        rmdir(self, cmake_folder)

        # Create a json helper file in order to populate package_info() at consume time
        save(self, self._components_helper_filepath, json.dumps(components, indent=4))

    def package_info(self):
        self.info.set_property("cmake_file_name", "absl")

        components_json_file = load(self, self._components_helper_filepath)
        abseil_components = json.loads(components_json_file)
        for pkgconfig_name, values in abseil_components.items():
            cmake_target = values["cmake_target"]
            self.info.components[pkgconfig_name].set_property("cmake_target_name", f"absl::{cmake_target}")
            self.info.components[pkgconfig_name].set_property("pkg_config_name", pkgconfig_name)
            self.info.components[pkgconfig_name].libs = values.get("libs", [])
            self.info.components[pkgconfig_name].defines = values.get("defines", [])
            self.info.components[pkgconfig_name].system_libs = values.get("system_libs", [])
            self.info.components[pkgconfig_name].frameworks = values.get("frameworks", [])
            self.info.components[pkgconfig_name].requires = values.get("requires", [])

    def _load_components_from_cmake_target_file(self, absl_target_file_path: Path):
        components: dict[str, dict[str, Any]] = {}

        abs_target_content = load(self, absl_target_file_path)

        # Replace the line endings to support building with MSys2 on Windows
        abs_target_content = abs_target_content.replace("\r\n", "\n")

        cmake_functions = re.findall(r"(?P<func>add_library|set_target_properties)[\n|\s]*\([\n|\s]*(?P<args>[^)]*)\)", abs_target_content)
        for (cmake_function_name, cmake_function_args) in cmake_functions:
            cmake_function_args = re.split(r"[\s|\n]+", cmake_function_args, maxsplit=2)

            cmake_imported_target_name = cmake_function_args[0]
            cmake_target_nonamespace = cmake_imported_target_name.replace("absl::", "")
            potential_lib_name = "absl_" + cmake_target_nonamespace

            components.setdefault(potential_lib_name, {"cmake_target": cmake_target_nonamespace})

            if cmake_function_name == "add_library":
                cmake_imported_target_type = cmake_function_args[1]
                if cmake_imported_target_type in ["STATIC", "SHARED"]:
                    components[potential_lib_name]["libs"] = [potential_lib_name] if cmake_target_nonamespace != "abseil_dll" else ["abseil_dll"]
            elif cmake_function_name == "set_target_properties":
                target_properties = re.findall(r"(?P<property>INTERFACE_COMPILE_DEFINITIONS|INTERFACE_INCLUDE_DIRECTORIES|INTERFACE_LINK_LIBRARIES)[\n|\s]+(?P<values>.+)", cmake_function_args[2])
                for target_property in target_properties:
                    property_type = target_property[0]
                    if property_type == "INTERFACE_LINK_LIBRARIES":
                        values_list = target_property[1].replace('"', "").split(";")
                        for dependency in values_list:
                            if dependency.startswith("absl::"):  # abseil targets
                                components[potential_lib_name].setdefault("requires", []).append(dependency.replace("absl::", "absl_"))
                            else:  # system libs or frameworks
                                if self.settings.os in ["Linux", "FreeBSD"]:
                                    if dependency == "Threads::Threads":
                                        components[potential_lib_name].setdefault("system_libs", []).append("pthread")
                                    elif "-lm" in dependency:
                                        components[potential_lib_name].setdefault("system_libs", []).append("m")
                                    elif "-lrt" in dependency:
                                        components[potential_lib_name].setdefault("system_libs", []).append("rt")
                                elif self.settings.os == "Windows":
                                    for system_lib in ["bcrypt", "advapi32", "dbghelp"]:
                                        if system_lib in dependency:
                                            components[potential_lib_name].setdefault("system_libs", []).append(system_lib)
                                elif is_apple_os(self):
                                    for framework in ["CoreFoundation"]:
                                        if framework in dependency:
                                            components[potential_lib_name].setdefault("frameworks", []).append(framework)
                    elif property_type == "INTERFACE_COMPILE_DEFINITIONS":
                        values_list = target_property[1].replace('"', "").split(";")
                        for definition in values_list:
                            if definition == r"\$<\$<PLATFORM_ID:AIX>:_LINUX_SOURCE_COMPAT>":
                                if self.settings.os == "AIX":
                                    components[potential_lib_name].setdefault("defines", []).append("_LINUX_SOURCE_COMPAT")
                            else:
                                components[potential_lib_name].setdefault("defines", []).append(definition)

        for component_name, values in components.items():
            requires = values.get("requires", [])
            if requires:
                values["requires"] = list(dict.fromkeys(dependency for dependency in requires if dependency != component_name))

            for key in ["defines", "frameworks", "libs", "system_libs"]:
                entries = values.get(key, [])
                if entries:
                    values[key] = list(dict.fromkeys(entries))

        return components

    @property
    def _components_helper_filepath(self):
        return self.folders.package / "lib" / "components.json"
